//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetStudioLeaveApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeave
    {
        public int LeaveId { get; set; }
        public int AvailableLeave { get; set; }
        public int LeaveStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime LeaveDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
